apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.deploymentname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.appname }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.auth.password }}
            - name: ME_CONFIG_MONGODB_SERVER
              value: {{ .Values.mongodb.servicename }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.servicename }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongodb.appname }}
  ports:
    - protocol: {{ .Values.mongodb.protocol }}
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}