apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoexpress.deploymentname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongoexpress.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoexpress.appname }}
    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.mongoexpress.image.repository }}:{{ .Values.mongoexpress.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "{{ .Values.mongoexpress.mongodb.host }}"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "{{ .Values.mongoexpress.mongodb.username }}"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "{{ .Values.mongoexpress.mongodb.password }}"
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: "{{ .Values.mongoexpress.mongodb.database }}"

---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoexpress.servicename }}
spec:
  type: {{ .Values.mongoexpress.service.type }}
  selector:
    app: {{ .Values.mongoexpress.appname }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP