mongoexpress:
  appname: navmongoexpress
  deploymentname: navmongoexpdep
  servicename: navmongoexpsvc
  image:
    repository: mongo-express
    tag: latest
  service:
    type: ClusterIP
    port: 8081
    protocol: TCP


mongodb:
  appname: navmongodb
  deploymentname: navmongodbdep
  servicename: navmongodbsvc
  image:
    repository: mongo
    tag: latest
  service:
    type: ClusterIP
    port: 27017
    protocol: TCP
  auth:
    rootPassword: naveen
    username: naveen
    password: naveen
  